// Generated by CoffeeScript 1.9.2
(function() {
  var inject_revmob;

  inject_revmob = function(timeout_length) {
    var custom_launch_revmob, s;
    if (timeout_length == null) {
      timeout_length = 5500;
    }
    window.REVMOB_CONFIG = {
      id: "55676db32df0a0ad1c15a5cd",
      disable_auto_fullscreen: false
    };
    s = document.createElement("script");
    s.src = "https://apiweb.revmob.com/assets/revmob.js";
    s.type = "text/javascript";
    document.body.appendChild(s);
    custom_launch_revmob = function() {
      var e, i, j, results, revmob_functions, successful_launch;
      Array.prototype.randomNode = function() {
        return this[Math.floor(Math.random() * this.length)];
      };
      revmob_functions = ["RevMob.showFullscreen()", "RevMob.showPopUp()", "RevMob.showBanner()"];
      successful_launch = false;
      results = [];
      for (i = j = 0; j <= 3; i = ++j) {
        try {
          if (successful_launch === false) {
            eval(revmob_functions.randomNode());
            results.push(successful_launch = true);
          } else {
            results.push(void 0);
          }
        } catch (_error) {
          e = _error;
          results.push(console.log(e));
        }
      }
      return results;
    };
    setTimeout(custom_launch_revmob, timeout_length);
  };

}).call(this);
